# Generated by Django 5.2.10 on 2026-01-16 07:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория растения',
                'verbose_name_plural': 'Категории растений',
            },
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('date', models.DateField(verbose_name='Дата')),
                ('temperature', models.FloatField(help_text='Температура в °C', verbose_name='Температура')),
                ('humidity', models.FloatField(help_text='Влажность в %', verbose_name='Влажность')),
                ('precipitation', models.FloatField(help_text='Осадки в мм', verbose_name='Осадки')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='Описание погоды')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
            ],
            options={
                'verbose_name': 'Погодные данные',
                'verbose_name_plural': 'Погодные данные',
            },
        ),
        migrations.CreateModel(
            name='PlantType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant_types', to='plants.plantcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Тип растения',
                'verbose_name_plural': 'Типы растений',
            },
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.planttype', verbose_name='Тип растения')),
            ],
            options={
                'verbose_name': 'Растение',
                'verbose_name_plural': 'Растения',
            },
        ),
        migrations.CreateModel(
            name='ProtectionAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pest_or_disease', models.CharField(max_length=100, verbose_name='Вредитель/Болезнь')),
                ('recommendation', models.TextField(verbose_name='Рекомендация')),
                ('plant_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.planttype', verbose_name='Тип растения')),
            ],
            options={
                'verbose_name': 'Совет по защите',
                'verbose_name_plural': 'Советы по защите',
            },
        ),
        migrations.CreateModel(
            name='WateringRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('water_amount', models.FloatField(help_text='Количество воды в литрах', verbose_name='Количество воды')),
                ('note', models.TextField(blank=True, verbose_name='Рекомендация')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plants.plant', verbose_name='Растение')),
            ],
            options={
                'verbose_name': 'Рекомендация по поливу',
                'verbose_name_plural': 'Рекомендации по поливу',
            },
        ),
    ]
