# Generated by Django 5.2.10 on 2026-01-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
