# Generated by Django 5.2.10 on 2026-01-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='planttype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='plant_types/', verbose_name='Фото растения'),
        ),
    ]
